version: '3.8'

services:
  api:
    build: .
    container_name: whisper-api
    ports:
      - "5000:5000"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: whisper-ngrok
    depends_on:
      - api
    environment:
      NGROK_AUTHTOKEN: 2z00gqHX9ew6WyavHQi0kBNZgKK_7pfxypVkasnxPE9LEHreC
    command: http api:5000