[versions]
agp = "8.6.0"
kotlin = "2.1.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
firebaseBom = "34.2.0"
googleServices = "4.4.3"
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
googleid = "1.1.1"
firebaseFirestore = "26.0.0"
circleImageView = "3.1.0"
firebaseStorageKtx = "21.0.2"
glide = "4.16.0"
imagePicker = "2.1"
retorfit2 = "2.9.0"
retofit2Gson = "2.9.0"
okhttp3 = "4.12.0"
navigation = "2.9.4"
hilt = "2.56.2"
hiltNav = "1.3.0"
shimmer = "0.5.0"
splashScreen = "1.0.1"
safeArgs = "2.9.4"
swiperefreshlayout = "1.2.0-alpha01"
media3exoplayer = "1.8.0"
pdfViewer = "2.3.7"
awsSdk = "2.69.0"
awsSdkMobileClient = "2.69.0"
lottie = "6.3.0"
flexBox = "3.0.0"
textDrawable = "1.0.1"
uiFirestore = "7.2.0"
kizitonwoseCalendar = "2.8.0"
desugar = "2.1.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom"}
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics"}
firebase-auth = { group = "com.google.firebase", name = "firebase-auth"}
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
circle-image = { module = "de.hdodenhof:circleimageview", version.ref = "circleImageView"}
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide"}
image-picker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagePicker"}
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retorfit2"}
retrofit2-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retofit2Gson"}
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3"}
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "hiltNav" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
splash-screen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
media3-exoplayer-core = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3exoplayer" }
media3-exoplayer-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3exoplayer" }
media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3exoplayer" }
media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3exoplayer" }
media3-exoplayer-rtsp = { group = "androidx.media3", name = "media3-exoplayer-rtsp", version.ref = "media3exoplayer" }
media3-datasource = { group = "androidx.media3", name = "media3-datasource", version.ref = "media3exoplayer" }
media3-datasource-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3exoplayer" }
pdf-viewer = { module = "io.github.afreakyelf:Pdf-Viewer", version.ref = "pdfViewer" }
aws-sdk = { group = "com.amazonaws", name = "aws-android-sdk-s3", version.ref = "awsSdk" }
aws-sdk-mobile-client = { group = "com.amazonaws", name = "aws-android-sdk-mobile-client", version.ref = "awsSdkMobileClient" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
flex-box = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexBox"}
textdrawable = { module = "io.github.mores:textdrawable", version.ref = "textDrawable"}
ui-firestore = { module = "com.firebaseui:firebase-ui-firestore", version.ref = "uiFirestore"}
kizitonwose-calendar = { module = "com.kizitonwose.calendar:view", version.ref = "kizitonwoseCalendar"}
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "safeArgs" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }



